# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not insert a new line between shell prompts
add_newline = false

# Always show the machine hostname
[hostname]
ssh_only = false

[username]
show_always = true

[aws]
disabled = true

[gcloud]
disabled = true
