# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not insert a new line between shell prompts
add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true
