[env]
TERM = "xterm-256color"

[keyboard]
bindings = [{ key = "N", mods = "Control | Shift", action = "CreateNewWindow" }]

[font]
size = 12

[font.normal]
family = "Iosevka Emoji"

[colors]
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#002b36"
foreground = "#839496"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#cf9a6b"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[colors.bright]
black = "#657b83"
red = "#d87979"
green = "#88cf76"
yellow = "#657b83"
blue = "#2699ff"
magenta = "#d33682"
cyan = "#43b8c3"
white = "#fdf6e3"
